const player = document.querySelector('.main_container'),
      playBtn = document.querySelector('.play-pause'),
      prevBtn = document.querySelector('.previous'),
      nextBtn = document.querySelector('.forward'),
      audio = document.querySelector('.audio'),
      progressContainer = document.querySelector('.progress__container'),
      progress = document.querySelector('.progress'),
      cover = document.querySelector('.cover'),
      backgr = document.querySelector('.background')